import { Inter } from "next/font/google";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import Sidebar from "./components/layout/Sidebar";
import AdSection from "./components/layout/AdSection";
import "./components/layoutStyle/layout.css";

const inter = Inter({ subsets: ["latin"] });
const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "CodeFarms",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header />
        <section className="layout">
          <Sidebar />
          {children}
          <AdSection />
        </section>
        <Footer />
      </body>
    </html>
  );
}
